### ISSUE TITLE
Administrator - Add Cost for Course Based on Location. [ Size : L]

### ISSUE THREAD

**Issue by shankerkarra** [tuojeanbaptiste/TeamC#17]
As a Administrator I should be able to add cost for each course against the location. So that students based on location / individual profile, they should be able to see the cost for the course.

Acceptance Criteria: Should be able to add multiple costs for each course.

Test Results: Should be able to see cost for each course, depending on Location/Student Profile.

**Comment by SanjoyGoswami1990** [comment]
Researching on how to this task in markdown language
